#!/bin/bash -login

#PBS -l walltime=48:00:00,nodes=1:ppn=8,mem=64GB
#PBS -N ciona_for_Wei_khgene2012_round2
#PBS -A ged
#PBS -M elijahlowe@gmail.com
#PBS -m abe

module load TopHat/2.0.8b
module load SAMTools
module load bwa
module load HTSeq/0.6.1
module load PySAM/0.6

WRKSP='/mnt/scratch/loweelij/Wei/round2/de_analysis'

reference='/mnt/home/loweelij/Wei/kh2012.fa'
gff='/mnt/home/loweelij/Wei/KH.KHGene.2013.gff3'

sample[1]=handrdnfgfr12hpf1_GGACCC_L005
sample[2]=handrdnfgfr12hpf2_CCTCGG_L005
sample[3]=handrlaz12hpf1_AAGGGA_L005
sample[4]=handrlaz12hpf2_TTCAGC_L005
sample[5]=handrnoggin12hpf1_CCTTCA_L005
sample[6]=handrnoggin12hpf2_AAGACG_L005
#rm -rf ${WRKSP}
mkdir ${WRKSP}
cd ${WRKSP}

bwa index ${reference}
for i in 1 2 3 4 5 6
do
    bwa mem ${reference} -t ${PBS_NUM_PPN} /mnt/home/loweelij/Wei/round2/${sample[i]}_R1_001.fastq.gz > ${sample[i]}.sam
    samtools view -Sb ${sample[i]}.sam > ${sample[i]}.unsorted.bam
    samtools sort ${sample[i]}.unsorted.bam ${sample[i]}
    samtools index ${sample[i]}.bam
    htseq-count --format=bam --stranded=no --type=CDS --order=pos --idattr=Parent ${sample[i]}.bam $gff > ${sample[i]}_htseq_counts.txt
done

qstat -f ${PBS_JOBID}